<a href="https://colab.research.google.com/github/scribenaz/CPP528/blob/main/Exercise_14_ex_7_1_fires.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shriver Smith  
Exercise 7-1: Prepare the Forest Fires Data  
Class: AIM111 - Introduction to Data Science  
Date: October 23, 2026

# Exercise 7-1: Prepare the Forest Fires data

## Read the data

In [1]:
import pandas as pd

In [2]:
fires_by_month = pd.read_pickle('fires_by_month.pkl')

In [3]:
# display the first 5 rows

In [4]:
fires_by_month.head()

  state  fire_year  fire_month  acres_burned  days_burning  fire_count
0    AK       1992           5        4202.0         135.0          14
1    AK       1992           6       86401.0         417.0          23
2    AK       1992           7       48516.7         500.0          26
3    AK       1992           8        3305.0          92.0           4
4    AK       1992           9          20.0           1.0           1

In [5]:
fires_by_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9300 entries, 0 to 9299
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         9300 non-null   category
 1   fire_year     9300 non-null   int64
 2   fire_month    9300 non-null   int64
 3   acres_burned  9300 non-null   float64
 4   days_burning  9300 non-null   float64
 5   fire_count    9300 non-null   int64
dtypes: category(1), float64(2), int64(3)
memory usage: 372.9 KB

## Add and modify columns

In [6]:
# add a column for the mean number of acres burned per day

In [7]:
fires_by_month['acres_per_day'] = fires_by_month.dropna().acres_burned / fires_by_month.dropna().days_burning
fires_by_month['acres_per_day'] = fires_by_month['acres_per_day']
fires_by_month.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day
0,AK,1992,5,4202.0,135.0,14,31.125926
1,AK,1992,6,86401.0,417.0,23,207.196643
2,AK,1992,7,48516.7,500.0,26,97.033400
3,AK,1992,8,3305.0,92.0,4,35.923913
4,AK,1992,9,20.0,1.0,1,20.000000

In [8]:
# add a column that uses a lambda to calculate the mean number of acres burned per day

In [9]:
fires_by_month['mean_acres_per_day'] = fires_by_month.apply(lambda x: x.acres_burned / x.days_burning if x.days_burning > 0 else 0, axis=1)
fires_by_month['mean_acres_per_day'] = fires_by_month['mean_acres_per_day']
fires_by_month.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,5,4202.0,135.0,14,31.125926,31.125926
1,AK,1992,6,86401.0,417.0,23,207.196643,207.196643
2,AK,1992,7,48516.7,500.0,26,97.033400,97.033400
3,AK,1992,8,3305.0,92.0,4,35.923913,35.923913
4,AK,1992,9,20.0,1.0,1,20.000000,20.000000

In [10]:
(fires_by_month['days_burning'] == 0).sum()

np.int64(3741)

In [11]:
fires_by_month[fires_by_month['days_burning'] == 0].head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
10,AK,1994,3,200.0,0.0,1,inf,0.0
29,AK,1997,3,300.0,0.0,1,inf,0.0
45,AK,2000,4,30.0,0.0,0,inf,0.0
55,AK,2001,10,20.5,0.0,0,inf,0.0
61,AK,2003,1,432.7,0.0,1,inf,0.0

In [12]:
# write a function to convert the fire_month column from an int value to a string value such as 'Jan', 'Feb', etc.

In [13]:

def convert_fire_month(row):
  if row.fire_month == 1:
    return 'Jan'
  elif row.fire_month == 2:
    return 'Feb'
  elif row.fire_month == 3:
    return 'Mar'
  elif row.fire_month == 4:
    return 'Apr'
  elif row.fire_month == 5:
    return 'May'
  elif row.fire_month == 6:
    return 'Jun'
  elif row.fire_month == 7:
    return 'Jul'
  elif row.fire_month == 8:
    return 'Aug'
  elif row.fire_month == 9:
    return 'Sep'
  elif row.fire_month == 10:
    return 'Oct'
  elif row.fire_month == 11:
    return 'Nov'
  else:
    return 'Dec'

In [14]:
# apply the function to the fire_month column

In [15]:
fires_by_month['fire_month'] = fires_by_month.apply(convert_fire_month, axis=1)
fires_by_month.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.125926
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.196643
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.033400
3,AK,1992,Aug,3305.0,92.0,4,35.923913,35.923913
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.000000

In [16]:
fires_by_month.head(5)

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.125926
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.196643
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.033400
3,AK,1992,Aug,3305.0,92.0,4,35.923913,35.923913
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.000000

## Work with indexes

In [17]:
# set an index on the state, fire_year, and fire_month columns

In [18]:
fires_by_month = fires_by_month.set_index(['state', 'fire_year', 'fire_month'])
fires_by_month.head()

                            acres_burned  days_burning  fire_count  \
state fire_year fire_month
AK    1992      May               4202.0         135.0          14
                Jun              86401.0         417.0          23
                Jul              48516.7         500.0          26
                Aug               3305.0          92.0           4
                Sep                 20.0           1.0           1

                            acres_per_day  mean_acres_per_day
state fire_year fire_month
AK    1992      May             31.125926           31.125926
                Jun            207.196643          207.196643
                Jul             97.033400           97.033400
                Aug             35.923913           35.923913
                Sep             20.000000           20.000000

In [19]:
# unstack the fire_month column and store the resulting DataFrame in a different variable

In [20]:
fires_by_month_wide = fires_by_month.unstack('fire_month')
fires_by_month_wide.head()

                acres_burned                                                  \
fire_month               Apr      Aug Dec Feb Jan       Jul       Jun    Mar
state fire_year
AK    1992               NaN   3305.0 NaN NaN NaN   48516.7   86401.0    NaN
      1993             113.0   1132.0 NaN NaN NaN  483493.3  197740.2    NaN
      1994               NaN  24139.0 NaN NaN NaN   50510.0  184428.0  200.0
      1995             810.6      NaN NaN NaN NaN   27856.0    5622.0    NaN
      1996             190.8     10.0 NaN NaN NaN   56143.0  446273.4    NaN

                              ... mean_acres_per_day                      \
fire_month           May Nov  ...                Dec Feb Jan         Jul
state fire_year               ...
AK    1992        4202.0 NaN  ...                NaN NaN NaN   97.033400
      1993        4152.0 NaN  ...                NaN NaN NaN  243.819112
      1994        1127.7 NaN  ...                NaN NaN NaN  102.246964
      1995        9394.0 NaN  ...                NaN NaN NaN   87.050000
      1996       92540.0 NaN  ...                NaN NaN NaN  186.521595


fire_month              Jun  Mar         May Nov         Oct   Sep
state fire_year
AK    1992       207.196643  NaN   31.125926 NaN         NaN  20.0
      1993       163.286705  NaN   37.071429 NaN         NaN   NaN
      1994       126.580645  0.0   49.030435 NaN  333.333333  12.5
      1995        20.078571  NaN   52.188889 NaN   14.000000   5.0
      1996       279.095310  NaN  451.414634 NaN  812.500000   NaN

[5 rows x 60 columns]

In [21]:
# reset the index for the fires_by_month DataFrame

In [22]:
fires_by_month = fires_by_month.reset_index()
fires_by_month.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.125926
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.196643
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.033400
3,AK,1992,Aug,3305.0,92.0,4,35.923913,35.923913
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.000000

In [23]:
fires_by_month.index

RangeIndex(start=0, stop=9300, step=1)

In [24]:
fires_by_month.tail()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
9295,WY,2015,Aug,4646.3,150.0,25,30.975333,30.975333
9296,WY,2015,Sep,5977.0,126.0,25,47.436508,47.436508
9297,WY,2015,Oct,10337.8,15.0,6,689.186667,689.186667
9298,WY,2015,Nov,509.3,3.0,4,169.766667,169.766667
9299,WY,2015,Dec,72.0,0.0,2,inf,0.000000

## Combine data

In [25]:
# create new fire data
new_fire = pd.DataFrame(data=[['CA',2021,'June',1000,100,1,10,10]], columns=fires_by_month.columns)
new_fire.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,CA,2021,June,1000,100,1,10,10

In [26]:
# add the new fire data to the end of the original DataFrame

In [27]:
fires_by_month = pd.concat([fires_by_month, new_fire])

In [28]:
# display the last five rows of the original DataFrame

In [29]:
fires_by_month.tail()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
9296,WY,2015,Sep,5977.0,126.0,25,47.436508,47.436508
9297,WY,2015,Oct,10337.8,15.0,6,689.186667,689.186667
9298,WY,2015,Nov,509.3,3.0,4,169.766667,169.766667
9299,WY,2015,Dec,72.0,0.0,2,inf,0.000000
0,CA,2021,June,1000.0,100.0,1,10.000000,10.000000

In [30]:
# reset the index for the original DataFrame, dropping the numeric index

In [31]:
fires_by_month = fires_by_month.reset_index(drop=True)

In [32]:
#display the last five rows of the DataFrame again

In [33]:
fires_by_month.tail()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
9296,WY,2015,Sep,5977.0,126.0,25,47.436508,47.436508
9297,WY,2015,Oct,10337.8,15.0,6,689.186667,689.186667
9298,WY,2015,Nov,509.3,3.0,4,169.766667,169.766667
9299,WY,2015,Dec,72.0,0.0,2,inf,0.000000
9300,CA,2021,June,1000.0,100.0,1,10.000000,10.000000

## Fix the SettingWithCopyWarning

In [36]:
# the cell that causes the SettingWithCopyWarning
fires_ak = fires_by_month.query('state == "AK"')
fires_ak.mean_acres_per_day = fires_ak.mean_acres_per_day.round()
fires_ak.head()

/tmp/ipykernel_3705/1405740276.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fires_ak.mean_acres_per_day = fires_ak.mean_acres_per_day.round()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.0
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.0
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.0
3,AK,1992,Aug,3305.0,92.0,4,35.923913,36.0
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.0

In [37]:
fires_by_month.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.125926
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.196643
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.033400
3,AK,1992,Aug,3305.0,92.0,4,35.923913,35.923913
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.000000

In [38]:
fires_ak = fires_by_month.query('state == "AK"').copy()
fires_ak.mean_acres_per_day = fires_ak.mean_acres_per_day.round()
fires_ak.head()

,state,fire_year,fire_month,acres_burned,days_burning,fire_count,acres_per_day,mean_acres_per_day
0,AK,1992,May,4202.0,135.0,14,31.125926,31.0
1,AK,1992,Jun,86401.0,417.0,23,207.196643,207.0
2,AK,1992,Jul,48516.7,500.0,26,97.033400,97.0
3,AK,1992,Aug,3305.0,92.0,4,35.923913,36.0
4,AK,1992,Sep,20.0,1.0,1,20.000000,20.0