<a href="https://colab.research.google.com/github/scribenaz/CPP528/blob/main/Exercise_12_ex_6_1_polling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shriver Smith  
Exercise 6-1 Clean the Poll Data  
Class: AIM111 - Introduction to Data Science  
Date: October 16, 2026

# Exercise 6-1: Clean the Polling data

## Read the data

In [1]:
import pandas as pd

In [4]:
polls = pd.read_csv('president_polls_2016.csv')

## Examine the data

In [ ]:
# run the info() method on the data

Columns that have missing values: grade, sample_size, rawpoll_johnson, rawpoll_mcmullin, adpoll_johnson, adpoll_mcmullin, multiversions, and url.

In [7]:
polls.info(verbose=True, memory_usage='deep', show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12624 entries, 0 to 12623
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             12624 non-null  int64
 1   branch            12624 non-null  object
 2   type              12624 non-null  object
 3   matchup           12624 non-null  object
 4   forecastdate      12624 non-null  object
 5   state             12624 non-null  object
 6   startdate         12624 non-null  object
 7   enddate           12624 non-null  object
 8   pollster          12624 non-null  object
 9   grade             11337 non-null  object
 10  samplesize        12621 non-null  float64
 11  population        12624 non-null  object
 12  poll_wt           12624 non-null  float64
 13  rawpoll_clinton   12624 non-null  float64
 14  rawpoll_trump     12624 non-null  float64
 15  rawpoll_johnson   8397 non-null   float64
 16  rawpoll_mcmullin  90 non-null     float64
 17  adjpoll_clinton   12624 non-null  float64
 18  adjpoll_trump     12624 non-null  float64
 19  adjpoll_johnson   8397 non-null   float64
 20  adjpoll_mcmullin  90 non-null     float64
 21  multiversions     36 non-null     object
 22  url               12621 non-null  object
 23  poll_id           12624 non-null  int64
 24  question_id       12624 non-null  int64
 25  createddate       12624 non-null  object
 26  timestamp         12624 non-null  object
dtypes: float64(10), int64(3), object(14)
memory usage: 11.7 MB

In [ ]:
# run the nunique() method on the data

Columns with only one value: cycle, branch, matchup, forecastdate, and multiversions

In [6]:
polls.nunique()

cycle                   1
branch                  1
type                    3
matchup                 1
forecastdate            1
state                  57
startdate             352
enddate               345
pollster              196
grade                  10
samplesize           1766
population              4
poll_wt              4399
rawpoll_clinton      1312
rawpoll_trump        1385
rawpoll_johnson       584
rawpoll_mcmullin       16
adjpoll_clinton     12569
adjpoll_trump       12582
adjpoll_johnson      6629
adjpoll_mcmullin       57
multiversions           1
url                  1304
poll_id              4208
question_id          4208
createddate           222
timestamp               3
dtype: int64

## Drop columns and rows

In [ ]:
# drop all rows except where the column is "now-cast"

In [10]:
polls = polls[polls.type == 'now-cast']

In [ ]:
# run the nunique() method again

In [11]:
polls.nunique()

cycle                  1
branch                 1
type                   1
matchup                1
forecastdate           1
state                 57
startdate            352
enddate              345
pollster             196
grade                 10
samplesize          1766
population             4
poll_wt             3894
rawpoll_clinton     1312
rawpoll_trump       1385
rawpoll_johnson      584
rawpoll_mcmullin      16
adjpoll_clinton     4202
adjpoll_trump       4199
adjpoll_johnson     2210
adjpoll_mcmullin      30
multiversions          1
url                 1304
poll_id             4208
question_id         4208
createddate          222
timestamp              1
dtype: int64

In [12]:
polls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4208 entries, 4208 to 8415
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cycle             4208 non-null   int64
 1   branch            4208 non-null   object
 2   type              4208 non-null   object
 3   matchup           4208 non-null   object
 4   forecastdate      4208 non-null   object
 5   state             4208 non-null   object
 6   startdate         4208 non-null   object
 7   enddate           4208 non-null   object
 8   pollster          4208 non-null   object
 9   grade             3779 non-null   object
 10  samplesize        4207 non-null   float64
 11  population        4208 non-null   object
 12  poll_wt           4208 non-null   float64
 13  rawpoll_clinton   4208 non-null   float64
 14  rawpoll_trump     4208 non-null   float64
 15  rawpoll_johnson   2799 non-null   float64
 16  rawpoll_mcmullin  30 non-null     float64
 17  adjpoll_clinton   4208 non-null   float64
 18  adjpoll_trump     4208 non-null   float64
 19  adjpoll_johnson   2799 non-null   float64
 20  adjpoll_mcmullin  30 non-null     float64
 21  multiversions     12 non-null     object
 22  url               4207 non-null   object
 23  poll_id           4208 non-null   int64
 24  question_id       4208 non-null   int64
 25  createddate       4208 non-null   object
 26  timestamp         4208 non-null   object
dtypes: float64(10), int64(3), object(14)
memory usage: 920.5+ KB

In [ ]:
# drop columns with a single value

In [13]:
polls = polls.drop(columns=['cycle', 'branch', 'type', 'matchup', 'forecastdate', 'multiversions', 'timestamp'])

In [14]:
polls.nunique()

state                 57
startdate            352
enddate              345
pollster             196
grade                 10
samplesize          1766
population             4
poll_wt             3894
rawpoll_clinton     1312
rawpoll_trump       1385
rawpoll_johnson      584
rawpoll_mcmullin      16
adjpoll_clinton     4202
adjpoll_trump       4199
adjpoll_johnson     2210
adjpoll_mcmullin      30
url                 1304
poll_id             4208
question_id         4208
createddate          222
dtype: int64

In [ ]:
# drop rows with "U.S." for the state

In [15]:
polls = polls[polls.state != 'U.S.']

In [17]:
polls.nunique()

state                 56
startdate            245
enddate              241
pollster             176
grade                 10
samplesize          1308
population             4
poll_wt             2874
rawpoll_clinton     1162
rawpoll_trump       1217
rawpoll_johnson      578
rawpoll_mcmullin      16
adjpoll_clinton     3100
adjpoll_trump       3097
adjpoll_johnson     1672
adjpoll_mcmullin      30
url                  847
poll_id             3102
question_id         3102
createddate          185
dtype: int64

Result: After running the commands to drop rows and columns we can see that our number of values the nunique() method produces has decreased by quite a bit. We are successfully cleaning up the data and narrowing down our focus while dropping information that may not actually be useful.

## Rename columns

In [ ]:
# rename all the rawpoll_* columns

In [18]:
polls = polls.rename(columns={
    'rawpoll_clinton': 'clinton_pct',
    'rawpoll_trump': 'trump_pct',
    'rawpoll_johnson': 'johnson_pct',
    'rawpoll_mcmullin': 'mcmullin_pct'})

## Fix data types

In [ ]:
# run the info() method again

In [19]:
polls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3102 entries, 4216 to 8415
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             3102 non-null   object
 1   startdate         3102 non-null   object
 2   enddate           3102 non-null   object
 3   pollster          3102 non-null   object
 4   grade             2961 non-null   object
 5   samplesize        3101 non-null   float64
 6   population        3102 non-null   object
 7   poll_wt           3102 non-null   float64
 8   clinton_pct       3102 non-null   float64
 9   trump_pct         3102 non-null   float64
 10  johnson_pct       2246 non-null   float64
 11  mcmullin_pct      30 non-null     float64
 12  adjpoll_clinton   3102 non-null   float64
 13  adjpoll_trump     3102 non-null   float64
 14  adjpoll_johnson   2246 non-null   float64
 15  adjpoll_mcmullin  30 non-null     float64
 16  url               3102 non-null   object
 17  poll_id           3102 non-null   int64
 18  question_id       3102 non-null   int64
 19  createddate       3102 non-null   object
dtypes: float64(10), int64(2), object(8)
memory usage: 508.9+ KB

In [20]:
# create a list of columns that should be datetimes

These are the columns that should be using the datetime data type: startdate, enddate, createddate.

In [22]:
date_columns = ['startdate', 'enddate', 'createddate']

In [23]:
# convert the columns to datetime

In [24]:
polls[date_columns] = polls[date_columns].apply(pd.to_datetime)

In [25]:
polls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3102 entries, 4216 to 8415
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             3102 non-null   object
 1   startdate         3102 non-null   datetime64[ns]
 2   enddate           3102 non-null   datetime64[ns]
 3   pollster          3102 non-null   object
 4   grade             2961 non-null   object
 5   samplesize        3101 non-null   float64
 6   population        3102 non-null   object
 7   poll_wt           3102 non-null   float64
 8   clinton_pct       3102 non-null   float64
 9   trump_pct         3102 non-null   float64
 10  johnson_pct       2246 non-null   float64
 11  mcmullin_pct      30 non-null     float64
 12  adjpoll_clinton   3102 non-null   float64
 13  adjpoll_trump     3102 non-null   float64
 14  adjpoll_johnson   2246 non-null   float64
 15  adjpoll_mcmullin  30 non-null     float64
 16  url               3102 non-null   object
 17  poll_id           3102 non-null   int64
 18  question_id       3102 non-null   int64
 19  createddate       3102 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(10), int64(2), object(5)
memory usage: 508.9+ KB

In [27]:
# convert the state and population columns to categories

In [28]:
polls = polls.astype({'state': 'category', 'population': 'category'})

In [29]:
polls.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3102 entries, 4216 to 8415
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             3102 non-null   category
 1   startdate         3102 non-null   datetime64[ns]
 2   enddate           3102 non-null   datetime64[ns]
 3   pollster          3102 non-null   object
 4   grade             2961 non-null   object
 5   samplesize        3101 non-null   float64
 6   population        3102 non-null   category
 7   poll_wt           3102 non-null   float64
 8   clinton_pct       3102 non-null   float64
 9   trump_pct         3102 non-null   float64
 10  johnson_pct       2246 non-null   float64
 11  mcmullin_pct      30 non-null     float64
 12  adjpoll_clinton   3102 non-null   float64
 13  adjpoll_trump     3102 non-null   float64
 14  adjpoll_johnson   2246 non-null   float64
 15  adjpoll_mcmullin  30 non-null     float64
 16  url               3102 non-null   object
 17  poll_id           3102 non-null   int64
 18  question_id       3102 non-null   int64
 19  createddate       3102 non-null   datetime64[ns]
dtypes: category(2), datetime64[ns](3), float64(10), int64(2), object(3)
memory usage: 469.2+ KB

In [ ]:
# Display the Polls data to see how it looks.

In [32]:
polls.head(5)

,state,startdate,enddate,pollster,grade,samplesize,population,poll_wt,clinton_pct,trump_pct,johnson_pct,mcmullin_pct,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin,url,poll_id,question_id,createddate
4216,New Mexico,2016-11-06,2016-11-06,Zia Poll,NaN,8439.0,lv,4.609492,46.0,44.0,6.0,NaN,45.04927,41.92541,7.657972,NaN,http://projects.fivethirtyeight.com.s3.amazona...,48614,76158,2016-11-07
4221,Virginia,2016-11-03,2016-11-04,Public Policy Polling,B+,1238.0,lv,3.923524,48.0,43.0,1.0,NaN,47.45700,42.35281,2.199139,NaN,http://www.publicpolicypolling.com/pdf/2015/PP...,48349,75743,2016-11-04
4223,Iowa,2016-11-01,2016-11-04,Selzer & Company,A+,800.0,lv,3.842234,39.0,46.0,6.0,NaN,39.36898,45.67372,5.995712,NaN,http://www.desmoinesregister.com/story/news/po...,48470,75957,2016-11-05
4225,Wisconsin,2016-10-26,2016-10-31,Marquette University,A,1255.0,lv,3.789957,46.0,40.0,4.0,NaN,46.10277,41.02478,2.856997,NaN,https://twitter.com/MULawPoll,48095,75264,2016-11-02
4226,North Carolina,2016-11-04,2016-11-06,Siena College,A,800.0,lv,3.774139,44.0,44.0,3.0,NaN,44.26048,44.98719,2.236248,NaN,http://www.nytimes.com/2016/11/08/upshot/trump...,48524,76066,2016-11-07