<a href="https://colab.research.google.com/github/scribenaz/CPP528/blob/main/Exercise_16_ex_8_1_fires.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Shriver Smith  
Exercise 8-1 Analyse the Forest Fires Data  
Class: AIM111 - Introduction to Data Science  
Date: October 27, 2026

# Exercise 8-1: Analyze the Forest Fires data

## Read the data

In [1]:
import pandas as pd

In [2]:
fires_by_month = pd.read_pickle('fires_by_month.pkl')

In [3]:
# display the first five rows

In [4]:
fires_by_month.head()

  state  fire_year  fire_month  acres_burned  days_burning  fire_count
0    AK       1992           5        4202.0         135.0          14
1    AK       1992           6       86401.0         417.0          23
2    AK       1992           7       48516.7         500.0          26
3    AK       1992           8        3305.0          92.0           4
4    AK       1992           9          20.0           1.0           1

In [5]:
fires_by_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9300 entries, 0 to 9299
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state         9300 non-null   category
 1   fire_year     9300 non-null   int64
 2   fire_month    9300 non-null   int64
 3   acres_burned  9300 non-null   float64
 4   days_burning  9300 non-null   float64
 5   fire_count    9300 non-null   int64
dtypes: category(1), float64(2), int64(3)
memory usage: 372.9 KB

## Group and aggregate the data

In [6]:
# group the data by state and year

In [7]:
fires_grouped = fires_by_month.groupby(['state', 'fire_year'], observed=True)

In [8]:
# sum the grouped data and store DataFrame in fires_by_year variable

In [9]:
fires_by_year = fires_grouped.sum()
fires_by_year

                 fire_month  acres_burned  days_burning  fire_count
state fire_year
AK    1992               35     142444.70        1145.0          68
      1993               30     686630.50        3373.0         144
      1994               48     261604.70        2517.0         126
      1995               41      43762.60         880.0          48
      1996               40     598407.20        2112.0          88
...                     ...           ...           ...         ...
WY    2011               77     134336.25         669.0         160
      2012               66     481206.46        1802.0         215
      2013               52      53884.90         742.0          40
      2014               75       7179.43         224.0          48
      2015               77      36233.50         351.0         107

[1148 rows x 4 columns]

In [10]:
# drop the fire_month column

In [11]:
fires_by_year.drop('fire_month', axis=1, inplace=True)
fires_by_year

                 acres_burned  days_burning  fire_count
state fire_year
AK    1992          142444.70        1145.0          68
      1993          686630.50        3373.0         144
      1994          261604.70        2517.0         126
      1995           43762.60         880.0          48
      1996          598407.20        2112.0          88
...                       ...           ...         ...
WY    2011          134336.25         669.0         160
      2012          481206.46        1802.0         215
      2013           53884.90         742.0          40
      2014            7179.43         224.0          48
      2015           36233.50         351.0         107

[1148 rows x 3 columns]

## Use pivot tables

In [12]:
# select rows where the year is 2013 or later. Then, reset the index for the DataFrame that's returned and assign the DataFrame to a variable named fires_recent.

In [13]:
fires_recent = fires_by_year.query('fire_year >= 2013').reset_index()
fires_recent.head()

  state  fire_year  acres_burned  days_burning  fire_count
0    AK       2013    1320518.50        4644.0         153
1    AK       2014     233426.40         571.0          43
2    AK       2015    5136372.99       16636.0         340
3    AL       2013      28015.65         115.0         581
4    AL       2014      35310.20         107.0         758

In [14]:
# use the pivot() method to pivot the data so the state values are used as row labels,
# fire_year values are used as column labels, and acres_burned values are used as data

In [15]:
fires_recent.pivot(index='state', columns='fire_year', values='acres_burned')

fire_year         2013           2014        2015
state
AK         1320518.500  233426.400000  5136372.99
AL           28015.650   35310.200000    28386.96
AR           11797.600   18521.800000    16302.96
AZ          102307.470  202212.510000   154720.38
CA          575555.650  543033.330000   844674.02
CO          161037.700   24488.270000    22599.10
CT                 NaN            NaN      108.70
DE              12.000            NaN       56.00
FL           74046.020  153560.600000   162845.80
GA            9781.680   15946.240000     8019.52
HI             738.000            NaN     4836.00
IA            2078.000    9603.500000    13139.85
ID          739424.400  198230.000000   790235.90
IL              84.000    2122.500000     1403.00
IN             716.000      65.700000      657.90
KS            6859.000   36497.400000   119054.62
KY           21302.700   39895.869996    18506.22
LA           20760.788   35929.020000    18293.07
MA                 NaN     372.500000      974.40
MD             273.000    1664.300000      888.30
ME             393.200      38.900000      327.50
MI             452.600     389.850000     3104.60
MN           20841.850    3124.000000    27254.40
MO            3210.960   20492.430000    10842.09
MS           19031.100   28713.000000    31251.30
MT           76471.520   33998.600000   348969.61
NC           11172.400   10958.100000     9272.62
ND            6074.800    3380.900000    24591.40
NE           10091.000   19444.600000    43558.75
NH              11.500      24.000000      501.86
NJ             903.500    9347.000000     2085.00
NM          284439.000   43357.370000    51571.08
NV          179702.850   69688.000000    23237.91
NY             832.100     663.400000     3639.00
OH            1191.140    2440.800000     1381.40
OK           28943.000  185987.900000   147565.40
OR          318386.850  932870.930000   578003.15
PA            1152.700    3443.680000     3166.84
PR            2473.400     212.000000     1311.60
RI                 NaN            NaN       47.45
SC            6687.200    8062.850000     4401.22
SD           14419.500   17951.200000    52758.22
TN            8941.300   15413.500000     7488.10
TX           59586.100  134069.300000   198621.98
UT           69872.800   26648.680000     9584.00
VA            5085.900   11252.300000     5505.50
VT             121.500      88.500000      222.00
WA          152719.800  448946.990000  1160483.43
WI            8712.950    2398.030000     1920.70
WV            9142.000   12547.500000    16479.77
WY           53884.900    7179.430000    36233.50

In [16]:
# use the pivot_table() method with the fires_by_month DataFrame to get the same result
# as the previous cell

In [17]:
fires_by_month.query('fire_year >= 2013').pivot_table(index='state', columns='fire_year', values='acres_burned', aggfunc='sum')

/tmp/ipykernel_2277/2537765164.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  fires_by_month.query('fire_year >= 2013').pivot_table(index='state', columns='fire_year', values='acres_burned', aggfunc='sum')

fire_year         2013           2014        2015
state
AK         1320518.500  233426.400000  5136372.99
AL           28015.650   35310.200000    28386.96
AR           11797.600   18521.800000    16302.96
AZ          102307.470  202212.510000   154720.38
CA          575555.650  543033.330000   844674.02
CO          161037.700   24488.270000    22599.10
CT               0.000       0.000000      108.70
DE              12.000       0.000000       56.00
FL           74046.020  153560.600000   162845.80
GA            9781.680   15946.240000     8019.52
HI             738.000       0.000000     4836.00
IA            2078.000    9603.500000    13139.85
ID          739424.400  198230.000000   790235.90
IL              84.000    2122.500000     1403.00
IN             716.000      65.700000      657.90
KS            6859.000   36497.400000   119054.62
KY           21302.700   39895.869996    18506.22
LA           20760.788   35929.020000    18293.07
MA               0.000     372.500000      974.40
MD             273.000    1664.300000      888.30
ME             393.200      38.900000      327.50
MI             452.600     389.850000     3104.60
MN           20841.850    3124.000000    27254.40
MO            3210.960   20492.430000    10842.09
MS           19031.100   28713.000000    31251.30
MT           76471.520   33998.600000   348969.61
NC           11172.400   10958.100000     9272.62
ND            6074.800    3380.900000    24591.40
NE           10091.000   19444.600000    43558.75
NH              11.500      24.000000      501.86
NJ             903.500    9347.000000     2085.00
NM          284439.000   43357.370000    51571.08
NV          179702.850   69688.000000    23237.91
NY             832.100     663.400000     3639.00
OH            1191.140    2440.800000     1381.40
OK           28943.000  185987.900000   147565.40
OR          318386.850  932870.930000   578003.15
PA            1152.700    3443.680000     3166.84
PR            2473.400     212.000000     1311.60
RI               0.000       0.000000       47.45
SC            6687.200    8062.850000     4401.22
SD           14419.500   17951.200000    52758.22
TN            8941.300   15413.500000     7488.10
TX           59586.100  134069.300000   198621.98
UT           69872.800   26648.680000     9584.00
VA            5085.900   11252.300000     5505.50
VT             121.500      88.500000      222.00
WA          152719.800  448946.990000  1160483.43
WI            8712.950    2398.030000     1920.70
WV            9142.000   12547.500000    16479.77
WY           53884.900    7179.430000    36233.50

## Work with bins

In [18]:
# reset the index for the DataFrame named fires_by_year

In [19]:
fires_by_year = fires_by_year.reset_index()
fires_by_year.head()

  state  fire_year  acres_burned  days_burning  fire_count
0    AK       1992      142444.7        1145.0          68
1    AK       1993      686630.5        3373.0         144
2    AK       1994      261604.7        2517.0         126
3    AK       1995       43762.6         880.0          48
4    AK       1996      598407.2        2112.0          88

In [20]:
# bin the data by decade

In [21]:
fires_by_year['decade'] = pd.cut(fires_by_year.fire_year, bins =[1989, 1999, 2009, 2019], labels=['1990s', '2000s', '2010s'])

In [22]:
# double-check the edge values

In [23]:
fires_by_year.head(25)

   state  fire_year  acres_burned  days_burning  fire_count decade
0     AK       1992  1.424447e+05        1145.0          68  1990s
1     AK       1993  6.866305e+05        3373.0         144  1990s
2     AK       1994  2.616047e+05        2517.0         126  1990s
3     AK       1995  4.376260e+04         880.0          48  1990s
4     AK       1996  5.984072e+05        2112.0          88  1990s
5     AK       1997  2.025818e+06        2295.0         128  1990s
6     AK       1998  1.206034e+05         435.0          31  1990s
7     AK       1999  1.005597e+06        2312.0         101  1990s
8     AK       2000  7.561614e+05        1745.0          51  2000s
9     AK       2001  2.197077e+05        1659.0          26  2000s
10    AK       2002  2.186329e+06        3207.0         100  2000s
11    AK       2003  6.013995e+05        1061.0          56  2000s
12    AK       2004  6.591431e+06        7783.0         167  2000s
13    AK       2005  4.635536e+06        7430.0         200  2000s
14    AK       2006  2.543659e+05         699.0          35  2000s
15    AK       2007  6.341360e+05        3506.0         139  2000s
16    AK       2008  9.226770e+04        1695.0          67  2000s
17    AK       2009  2.949289e+06        5389.0         133  2000s
18    AK       2010  1.137138e+06        6223.0         214  2010s
19    AK       2011  2.927164e+05        1686.0          70  2010s
20    AK       2012  3.003448e+05        1265.0          95  2010s
21    AK       2013  1.320519e+06        4644.0         153  2010s
22    AK       2014  2.334264e+05         571.0          43  2010s
23    AK       2015  5.136373e+06       16636.0         340  2010s
24    AL       1992  1.098000e+03           1.0           4  1990s

In [24]:
# drop the fire_year column and assign the DataFrame that's returned to a variable named fires_by_decade

In [26]:
fires_by_decade = fires_by_year.drop('fire_year', axis=1)
fires_by_decade.head()

  state  acres_burned  days_burning  fire_count decade
0    AK      142444.7        1145.0          68  1990s
1    AK      686630.5        3373.0         144  1990s
2    AK      261604.7        2517.0         126  1990s
3    AK       43762.6         880.0          48  1990s
4    AK      598407.2        2112.0          88  1990s

In [25]:
# group by the state and decade columns and sum the data

In [27]:
fires_by_decade = fires_by_decade.groupby(['state', 'decade'], observed=True).sum()
fires_by_decade

              acres_burned  days_burning  fire_count
state decade
AK    1990s   4.884868e+06       15069.0         734
      2000s   1.892062e+07       34174.0         974
      2010s   8.420518e+06       31025.0         915
AL    1990s   1.945928e+05         214.0         216
      2000s   4.088805e+05        1863.0         535
...                    ...           ...         ...
WV    2000s   2.308489e+05         804.0        1418
      2010s   8.406907e+04         393.0         724
WY    1990s   4.240744e+05         675.0         450
      2000s   1.166740e+06        7382.0         720
      2010s   7.993449e+05        6990.0         687

[152 rows x 3 columns]